
language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
    - sudo apt-get update
    - wget https://launchpad.net/ubuntu/+archive/primary/+files/libzmq1_2.1.11-1ubuntu1_amd64.deb -qO /tmp/libzmq1.deb
    - sudo dpkg -i /tmp/libzmq1.deb

install:
    - cpanm --notest Module::ScanDeps AnyEvent EV Test::Exception

before_script:
    - >-
        PERL5LIB=/home/travis/build/calid/zmq-ffi/lib
        scandeps.pl lib/ZMQ/* 2>/dev/null
        | awk '{print $1}'
        | sed -e "s/'//g"
        | cpanm --notest || /bin/true

script: xt/test_versions.sh
