
language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
    - sudo apt-get update
    - sudo apt-get install libzmq3
    - sudo apt-get install apt-file
    - apt-file update
    - apt-file list libzmq3

install:
    - cpanm --notest Module::ScanDeps AnyEvent EV

before_script:
    - >-
        echo $PERL_CPANM_OPT &&
        PERL5LIB=/home/travis/build/calid/zmq-ffi/lib
        scandeps.pl lib/ZMQ/* 2>/dev/null
        | awk '{print $1}'
        | sed -e "s/'//g"
        | cpanm --notest || /bin/true

script: prove -lvr t
